# vi: set filetype=dockerfile
FROM rust:slim as builder
RUN cargo install cargo-build-deps
WORKDIR /build
RUN USER=root cargo init --bin --name=placeholder
COPY Cargo.* ./
RUN cargo build-deps
COPY src ./src
RUN cargo build

FROM debian
RUN apt-get update && \
    apt-get install -y tcpdump iperf && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
COPY --from=builder /build/target/debug/wsvpn /wsvpn
CMD ["/wsvpn", "help"]